/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ak-47s/scene.gltf -o src/components/AK47.jsx -r public 
Author: Frostoise (https://sketchfab.com/Frostoise)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ak-47s-07065c43bdb2459ca8faf7a99b075b9b
Title: AK-47S
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AK47(props) {
	const { nodes, materials } = useGLTF("/models/ak-47s/scene.gltf");
	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<mesh
					geometry={nodes.Cube007_Material_0.geometry}
					material={materials.Material}
					position={[0, -17.011, -180.319]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.Cylinder002_Scope001_0.geometry}
					material={materials["Scope.001"]}
					position={[0, 162.317, 34.38]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/models/ak-47s/scene.gltf");
