/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ar-15/scene.gltf -o src/components/AR15.jsx -r public 
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ar-15-style-rifle-50d33435445e439c95e3b36e9d4bd798
Title: AR-15 style rifle
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AR15(props) {
	const { nodes, materials } = useGLTF("/models/ar-15/scene.gltf");
	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<group position={[-9.802, -31.795, 26.348]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
					<mesh geometry={nodes.ar15_ar15_1_0.geometry} material={materials.ar15_1} />
					<mesh geometry={nodes.ar15_ar_15_2_0.geometry} material={materials.ar_15_2} />
				</group>
				<mesh
					geometry={nodes.dust_cover_ar15_1_0.geometry}
					material={materials.ar15_1}
					position={[13.92, -4.373, -69.078]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.ar15005_ar15_1_0.geometry}
					material={materials.ar15_1}
					position={[-8.318, 21.922, 64.202]}
					rotation={[-Math.PI / 2, 0, -0.008]}
					scale={100}
				/>
				<mesh
					geometry={nodes.bolt_carrier_ar15_1_0.geometry}
					material={materials.ar15_1}
					position={[6.452, 2.621, -63.89]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.forward_assist_ar15_1_0.geometry}
					material={materials.ar15_1}
					position={[25.474, 0.173, 58.087]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.magazine_ar_15_2_0.geometry}
					material={materials.ar_15_2}
					position={[-0.266, -18.233, -41.021]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.belt_ar_15_2_0.geometry}
					material={materials.ar_15_2}
					position={[5.459, -15.16, -293.621]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.trigger_ar15_1_0.geometry}
					material={materials.ar15_1}
					position={[-2.024, -52.55, 2.282]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.acog_optic001_0.geometry}
					material={materials["optic.001"]}
					position={[1.048, 56.527, 1.35]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.bullets_bullets_0.geometry}
					material={materials.bullets}
					position={[-3.864, -87.155, -39.885]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
				<mesh
					geometry={nodes.gps_gps_0.geometry}
					material={materials.material}
					position={[20.915, -9.295, 265.651]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/models/ar-15/scene.gltf");
