/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/bt-spr-300/scene.gltf -o src/components/BT300.jsx -r public 
Author: m.daneshyab (https://sketchfab.com/m.daneshyab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bt-spr-300-30d47cacabbe4de7ab7c25bbfef3a41b
Title: B&T SPR 300
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function BT300(props) {
	const { nodes, materials } = useGLTF("/models/bt-spr-300/scene.gltf");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-1.857, 0, 0]} scale={1.936}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group rotation={[-Math.PI / 2, 0, 0]}>
						<group position={[0, -14.55, 4.55]}>
							<mesh
								geometry={nodes.Bolt_addtionalParts_0.geometry}
								material={materials.addtionalParts}
								position={[0, 14.55, -4.55]}
							/>
						</group>
						<group position={[0, -1.082, 1.832]}>
							<mesh
								geometry={nodes.Mag_Mag_0.geometry}
								material={materials.material}
								position={[0, 1.082, -1.832]}
							/>
						</group>
						<group position={[0.269, -1.927, 2.823]}>
							<mesh
								geometry={nodes.Bullet_Bullet_0.geometry}
								material={materials.Bullet}
								position={[0, 2.174, 0.452]}
							/>
						</group>
						<group position={[-1.95, -21.45, 1.044]}>
							<mesh
								geometry={nodes.Stuck_Stuck_0.geometry}
								material={materials.Stuck}
								position={[1.95, 21.45, -1.044]}
							/>
						</group>
						<group position={[0, -15, -0.6]}>
							<mesh
								geometry={nodes.Handel_Handel_0.geometry}
								material={materials.Handel}
								position={[0, 15, 0.6]}
							/>
						</group>
						<mesh geometry={nodes.MainBody_Body_0.geometry} material={materials.Body} />
						<mesh geometry={nodes.Scope_Scope_0.geometry} material={materials.Scope} />
						<mesh
							geometry={nodes.Supresser_addtionalParts_0.geometry}
							material={materials.addtionalParts}
						/>
						<mesh
							geometry={nodes.MainBodyFront_addtionalParts_0.geometry}
							material={materials.addtionalParts}
						/>
						<mesh
							geometry={nodes.Follower_Mag_0.geometry}
							material={materials.material}
							position={[0, 0, -0.03]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/bt-spr-300/scene.gltf");
