/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/russian_soldier.glb -t 
Author: Bzovius (https://sketchfab.com/Bzovius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/russian-soldier-66df4b2856194d40a546afe2d1d77cfe
Title: Russian Soldier
*/

import { useGLTF } from "@react-three/drei";

export default function Russian_soldier(props) {
	const { nodes, materials } = useGLTF("/models/russian_soldier.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, Math.PI / 1.5]} scale={0.003}>
				<mesh geometry={nodes.Object_2.geometry} material={materials.material_1} />
				<mesh geometry={nodes.Object_3.geometry} material={materials.material} />
				<mesh geometry={nodes.Object_4.geometry} material={materials.material} />
				<mesh geometry={nodes.Object_5.geometry} material={materials.material} />
			</group>
		</group>
	);
}

useGLTF.preload("/models/russian_soldier.glb");
