/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/smg/scene.gltf -o src/components/SMG.jsx -r public 
Author: McCarthy3D (https://sketchfab.com/joshuawatt811)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halo-2-anniversary-smg-b750ee3892c1427ab9e768313ba38f6d
Title: Halo 2 anniversary - SMG
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SMG(props) {
	const { nodes, materials } = useGLTF("/models/smg/scene.gltf");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.057}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						geometry={nodes.Scope_SMG_Scope_Mat_0.geometry}
						material={materials.SMG_Scope_Mat}
						position={[0, -10, 0]}
					/>
					<mesh geometry={nodes.Laser_SMG_Scope_Mat_0.geometry} material={materials.SMG_Scope_Mat} />
					<mesh geometry={nodes.Silencer_SMG_Scope_Mat_0.geometry} material={materials.SMG_Scope_Mat} />
					<mesh geometry={nodes.Magazine_SMG_Scope_Mat_0.geometry} material={materials.SMG_Scope_Mat} />
					<mesh geometry={nodes.Foregrip_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Slide_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Body_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Grip_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Trigger_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Latch_1_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Latch_2_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Stock_Slide_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
					<mesh geometry={nodes.Stock_SMG_Body_Mat_0.geometry} material={materials.SMG_Body_Mat} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/smg/scene.gltf");
