/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/soldier/scene.gltf -o src/components/Soldier.jsx -r public 
Author: buh (https://sketchfab.com/inobi_ll)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polish-soldier-fb96a663fc4a4246a57ca85de3228c00
Title: Polish soldier
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Soldier(props) {
	const { nodes, materials } = useGLTF("/models/soldier/scene.gltf");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.952}>
				<group position={[0, 0.323, 1.24]}>
					<primitive object={nodes.base_soldier1_rootJoint} />
					<group position={[-0.091, -0.528, 0.006]} rotation={[-0.019, -0.136, -0.119]}>
						<mesh
							geometry={nodes.WZ96_Beryl_mag_0.geometry}
							material={materials.WZ96_Beryl}
							position={[0.002, -0.003, 0.001]}
							rotation={[3.119, -0.297, 1.538]}
						/>
					</group>
					<group position={[0.012, -0.531, 0.02]} rotation={[-0.028, -0.189, 0.051]}>
						<mesh
							geometry={nodes.WZ96_Beryl_mag_2_0.geometry}
							material={materials.WZ96_Beryl}
							position={[0.002, -0.003, 0.001]}
							rotation={[-3.134, -0.311, 1.539]}
						/>
					</group>
					<group position={[0.118, -0.521, 0.019]} rotation={[0.056, -0.16, 0.482]}>
						<mesh
							geometry={nodes.WZ96_Beryl_mag_3_0.geometry}
							material={materials.WZ96_Beryl}
							position={[0.002, -0.005, 0.001]}
							rotation={[-3.137, -0.298, 1.577]}
						/>
					</group>
					<skinnedMesh
						geometry={nodes.boot_war1_0.geometry}
						material={materials.boot_war1}
						skeleton={nodes.boot_war1_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.magb_0.geometry}
						material={materials.magb}
						skeleton={nodes.magb_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.magb_2_0.geometry}
						material={materials.magb}
						skeleton={nodes.magb_2_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.magb_3_0.geometry}
						material={materials.magb}
						skeleton={nodes.magb_3_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.pol_bproof_0.geometry}
						material={materials.pol_bproof}
						skeleton={nodes.pol_bproof_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.pol_hand_0.geometry}
						material={materials.pol_hand}
						skeleton={nodes.pol_hand_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.pol_head_0.geometry}
						material={materials.pol_head}
						skeleton={nodes.pol_head_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.pol_jaket_0.geometry}
						material={materials.pol_jaket}
						skeleton={nodes.pol_jaket_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.pol_pants_0.geometry}
						material={materials.pol_pants}
						skeleton={nodes.pol_pants_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.RGZ89_1_0.geometry}
						material={materials.RGZ89}
						skeleton={nodes.RGZ89_1_0.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.RGZ89_2_0.geometry}
						material={materials.RGZ89}
						skeleton={nodes.RGZ89_2_0.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/soldier/scene.gltf");
